"""initial schema

Revision ID: c800a33bc3e9
Revises: 
Create Date: 2026-08-29 23:45:38.889970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c800a33bc3e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('default_manufacturer_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.Enum('INSPECTOR', 'SUPERVISOR', 'ADMINISTRATOR', name='rolename'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('rule_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_pack_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'INFO', name='severity'), nullable=False),
    sa.Column('applicability', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('validation_logic', sa.JSON(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=True),
    sa.Column('counts_toward_score', sa.Boolean(), nullable=True),
    sa.Column('expected_condition', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_pack_id'], ['rule_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_pack_code', 'rules', ['rule_pack_id', 'rule_code'], unique=True)
    op.create_index(op.f('ix_rules_rule_code'), 'rules', ['rule_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('batch_lot', sa.String(length=100), nullable=True),
    sa.Column('manufacturer_name', sa.String(length=255), nullable=True),
    sa.Column('supply_type', sa.Enum('DOMESTIC', 'IMPORTED', name='supplytype'), nullable=False),
    sa.Column('inspection_location', sa.String(length=255), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('listing_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'EVIDENCE_UPLOADED', 'OCR_COMPLETE', 'DECLARATIONS_EXTRACTED', 'ANALYZED', 'REVIEWED', 'FINALIZED', name='inspectionstatus'), nullable=False),
    sa.Column('overall_result', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'REVIEW_REQUIRED', name='overallresult'), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('rule_pack_id_used', sa.Integer(), nullable=True),
    sa.Column('demo_scenario', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['rule_pack_id_used'], ['rule_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspection_status_result', 'inspections', ['status', 'overall_result'], unique=False)
    op.create_index(op.f('ix_inspections_overall_result'), 'inspections', ['overall_result'], unique=False)
    op.create_index(op.f('ix_inspections_reference_code'), 'inspections', ['reference_code'], unique=True)
    op.create_index(op.f('ix_inspections_status'), 'inspections', ['status'], unique=False)
    op.create_table('compliance_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('rule_pack_id', sa.Integer(), nullable=False),
    sa.Column('run_by', sa.Integer(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('overall_result', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'REVIEW_REQUIRED', name='overallresult'), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['rule_pack_id'], ['rule_packs.id'], ),
    sa.ForeignKeyConstraint(['run_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.Enum('FRONT', 'BACK', 'SIDE', 'ADDITIONAL', 'LISTING', name='evidencetype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('PDF', 'DOCX', name='reporttype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.Enum('GENERIC_NAME', 'MANUFACTURER_NAME', 'ADDRESS', 'COUNTRY_OF_ORIGIN', 'NET_QUANTITY', 'MRP', 'MFG_DATE', 'BEST_BEFORE', 'CONSUMER_CARE', 'UNIT_SALE_PRICE', 'OTHER', name='declarationfield'), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_evidence_id', sa.Integer(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('is_manually_edited', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_declaration_inspection_field', 'declarations', ['inspection_id', 'field_key'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compliance_run_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'REVIEW', 'NON_COMPLIANT', 'NOT_APPLICABLE', name='findingstatus'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'INFO', name='severity'), nullable=True),
    sa.Column('detected_value', sa.Text(), nullable=True),
    sa.Column('expected_condition', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('evidence_bounding_box', sa.JSON(), nullable=True),
    sa.Column('counts_toward_score', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['compliance_run_id'], ['compliance_runs.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('engine_name', sa.String(length=100), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('requires_manual_entry', sa.Boolean(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officer_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('CONFIRMED', 'DISMISSED', 'MARKED_FOR_REVIEW', name='decisiontype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officer_decisions')
    op.drop_table('ocr_results')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_declaration_inspection_field', table_name='declarations')
    op.drop_table('declarations')
    op.drop_table('reports')
    op.drop_table('evidence')
    op.drop_table('compliance_runs')
    op.drop_index(op.f('ix_inspections_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_reference_code'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_overall_result'), table_name='inspections')
    op.drop_index('ix_inspection_status_result', table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rules_rule_code'), table_name='rules')
    op.drop_index('ix_rule_pack_code', table_name='rules')
    op.drop_table('rules')
    op.drop_table('rule_packs')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
